//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int ID { get; set; }
        public string Customer { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string ImageLink { get; set; }
        public string RefererLink { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> ClickCount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public string SectionID { get; set; }
        public bool IsDefault { get; set; }
    }
}
