//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public int ChapterID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string ChapterName { get; set; }
        public Nullable<int> id { get; set; }
    }
}
