//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleAPI
    {
        public int id { get; set; }
        public string GoogleScript { get; set; }
        public string GoogleJson { get; set; }
        public string ViewID { get; set; }
    }
}
