//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageSection
    {
        public string ID { get; set; }
        public string SectionName { get; set; }
        public int CategoryID { get; set; }
        public int PostsQuantity { get; set; }
        public string Description { get; set; }
        public bool isModable { get; set; }
    }
}
