//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerPage
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string Địa_Chỉ { get; set; }
        public Nullable<int> Hotline { get; set; }
        public string Title { get; set; }
        public string Introduce { get; set; }
        public string DichVu { get; set; }
        public string LienKet { get; set; }
    }
}
