//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageData
    {
        public int ID { get; set; }
        public string Time { get; set; }
        public string Address { get; set; }
        public Nullable<double> PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lng { get; set; }
        public bool Status { get; set; }
        public string MetaKeywordDefault { get; set; }
        public string MetaDescriptionDefault { get; set; }
    }
}
