//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopManagement
    {
        public int ID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Url { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool Status { get; set; }
        public string Content { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> UserTime { get; set; }
        public Nullable<bool> Payment { get; set; }
        public Nullable<double> Money { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
