//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempAdSection
    {
        public string ID { get; set; }
        public string SectionName { get; set; }
        public string Size { get; set; }
        public string ImageLink { get; set; }
        public string RefererLink { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Status { get; set; }
        public string ImageAltInfo { get; set; }
        public string Page { get; set; }
    }
}
