//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topmenu
    {
        public int id { get; set; }
        public string tenduong { get; set; }
        public string diachi { get; set; }
        public string Email { get; set; }
        public string giolamviec { get; set; }
        public Nullable<int> hotline { get; set; }
    }
}
