//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGrantPermission
    {
        public int PermissionId { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
    
        public virtual UserAdministrator UserAdministrator { get; set; }
        public virtual UserPermission UserPermission { get; set; }
    }
}
