//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPost
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string Content { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Tags { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ViewNo { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserAdministrator UserAdministrator { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
